import { DatabaseSync } from "node:sqlite";
import { mkdirSync } from "node:fs";
import path from "node:path";
import type { Ticket } from "./inbox";

const filename=process.env.DATABASE_FILE||(process.env.VERCEL?"/tmp/support-copilot.db":".data/support-copilot.db");
let connection:DatabaseSync|undefined;
function database(){if(connection)return connection;if(filename!==":memory:")mkdirSync(path.dirname(filename),{recursive:true});const db=new DatabaseSync(filename);db.exec(`PRAGMA busy_timeout=5000; PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS tickets(id TEXT PRIMARY KEY,repository TEXT NOT NULL,source_url TEXT NOT NULL,subject TEXT NOT NULL,payload_json TEXT NOT NULL,source_updated_at TEXT NOT NULL,synced_at TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS ticket_state(ticket_id TEXT PRIMARY KEY,status TEXT NOT NULL CHECK(status IN ('inbox','assigned','resolved')),updated_at TEXT NOT NULL,FOREIGN KEY(ticket_id) REFERENCES tickets(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS github_webhook_events(delivery_id TEXT PRIMARY KEY,event TEXT NOT NULL,action TEXT NOT NULL,repository TEXT NOT NULL,ticket_id TEXT,received_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS monitored_repositories(full_name TEXT PRIMARY KEY,added_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS app_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS tickets_repository_updated ON tickets(repository,source_updated_at DESC);`);const columns=db.prepare("PRAGMA table_info(tickets)").all() as{name:string}[];if(!columns.some(column=>column.name==="active"))db.exec("ALTER TABLE tickets ADD COLUMN active INTEGER NOT NULL DEFAULT 1");connection=db;return db}

export type TicketStatus="inbox"|"assigned"|"resolved";
export function storageInfo(){const db=database();const tickets=db.prepare("SELECT COUNT(*) AS count FROM tickets").get() as{count:number},active=db.prepare("SELECT COUNT(*) AS count FROM tickets WHERE active=1").get() as{count:number},webhooks=db.prepare("SELECT COUNT(*) AS count FROM github_webhook_events").get() as{count:number};return{engine:"sqlite",durable:!process.env.VERCEL&&filename!==":memory:",ticketCount:Number(tickets.count),activeTicketCount:Number(active.count),webhookEventCount:Number(webhooks.count)}}
export function saveTickets(tickets:Ticket[]){const db=database(),now=new Date().toISOString();const upsert=db.prepare(`INSERT INTO tickets(id,repository,source_url,subject,payload_json,source_updated_at,synced_at,active) VALUES(?,?,?,?,?,?,?,1) ON CONFLICT(id) DO UPDATE SET repository=excluded.repository,source_url=excluded.source_url,subject=excluded.subject,payload_json=excluded.payload_json,source_updated_at=excluded.source_updated_at,synced_at=excluded.synced_at,active=1`);db.exec("BEGIN");try{for(const ticket of tickets)upsert.run(ticket.id,ticket.repository,ticket.sourceUrl,ticket.subject,JSON.stringify(ticket),ticket.createdAt,now);db.exec("COMMIT")}catch(error){db.exec("ROLLBACK");throw error}}
export function saveWebhookDelivery(input:{deliveryId:string;event:string;action:string;ticket:Ticket;active:boolean}){const db=database(),now=new Date().toISOString();db.exec("BEGIN IMMEDIATE");try{const inserted=db.prepare("INSERT OR IGNORE INTO github_webhook_events(delivery_id,event,action,repository,ticket_id,received_at) VALUES(?,?,?,?,?,?)").run(input.deliveryId,input.event,input.action,input.ticket.repository,input.ticket.id,now);if(Number(inserted.changes)===0){db.exec("ROLLBACK");return{duplicate:true}}db.prepare(`INSERT INTO tickets(id,repository,source_url,subject,payload_json,source_updated_at,synced_at,active) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET repository=excluded.repository,source_url=excluded.source_url,subject=excluded.subject,payload_json=excluded.payload_json,source_updated_at=excluded.source_updated_at,synced_at=excluded.synced_at,active=excluded.active`).run(input.ticket.id,input.ticket.repository,input.ticket.sourceUrl,input.ticket.subject,JSON.stringify(input.ticket),input.ticket.createdAt,now,input.active?1:0);db.exec("COMMIT");return{duplicate:false,ticketId:input.ticket.id,active:input.active,receivedAt:now}}catch(error){db.exec("ROLLBACK");throw error}}
export function statuses(ids:string[]){if(!ids.length)return{};const db=database(),placeholders=ids.map(()=>"?").join(",");const rows=db.prepare(`SELECT ticket_id,status FROM ticket_state WHERE ticket_id IN (${placeholders})`).all(...ids) as {ticket_id:string;status:TicketStatus}[];return Object.fromEntries(rows.map(row=>[row.ticket_id,row.status])) as Record<string,TicketStatus>}
export function setStatus(id:string,status:TicketStatus){const db=database(),exists=db.prepare("SELECT 1 FROM tickets WHERE id=?").get(id);if(!exists)return null;const now=new Date().toISOString();db.prepare(`INSERT INTO ticket_state(ticket_id,status,updated_at) VALUES(?,?,?) ON CONFLICT(ticket_id) DO UPDATE SET status=excluded.status,updated_at=excluded.updated_at`).run(id,status,now);return{ticketId:id,status,updatedAt:now}}
const defaults=["vercel/next.js","langchain-ai/langchain","supabase/supabase"];
function seedRepositories(){const db=database();if(db.prepare("SELECT 1 FROM app_meta WHERE key='repositories_seeded'").get())return;const insert=db.prepare("INSERT OR IGNORE INTO monitored_repositories(full_name,added_at) VALUES(?,?)"),now=new Date().toISOString();db.exec("BEGIN");try{for(const repo of defaults)insert.run(repo,now);db.prepare("INSERT INTO app_meta(key,value) VALUES('repositories_seeded','1')").run();db.exec("COMMIT")}catch(error){db.exec("ROLLBACK");throw error}}
export function repositories(){seedRepositories();return(database().prepare("SELECT full_name FROM monitored_repositories ORDER BY full_name").all()as{full_name:string}[]).map(row=>row.full_name)}
export function addRepository(fullName:string){seedRepositories();if(repositories().length>=20)throw new Error("repository_limit_reached");const addedAt=new Date().toISOString();database().prepare("INSERT INTO monitored_repositories(full_name,added_at) VALUES(?,?)").run(fullName,addedAt);return{fullName,addedAt}}
export function removeRepository(fullName:string){seedRepositories();const result=database().prepare("DELETE FROM monitored_repositories WHERE full_name=?").run(fullName);return Number(result.changes)>0}
